# Generated by Django 3.2 on 2021-07-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210701_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='crypto',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='currencies',
            field=models.ManyToManyField(to='portfolio.Crypto'),
        ),
    ]
