# Generated by Django 3.2 on 2021-07-02 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210702_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='amount',
        ),
        migrations.CreateModel(
            name='UpdatePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.crypto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.updateportfolio'),
        ),
    ]
