# Generated by Django 3.2 on 2021-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210702_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='update',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updates',
            field=models.ManyToManyField(to='portfolio.UpdatePortfolio'),
        ),
    ]
