# Generated by Django 3.2 on 2021-07-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210702_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateportfolio',
            old_name='amount',
            new_name='amount_usd',
        ),
        migrations.AddField(
            model_name='updateportfolio',
            name='crypto_quantity',
            field=models.FloatField(default=0),
        ),
    ]
