# Generated by Django 3.2 on 2021-07-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210702_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateportfolio',
            name='crypto',
        ),
        migrations.AddField(
            model_name='crypto',
            name='change',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='updateportfolio',
            name='amount_usd',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='updateportfolio',
            name='crypto_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
