# Generated by Django 3.2 on 2021-07-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_crypto_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='updates',
        ),
        migrations.AlterField(
            model_name='crypto',
            name='change',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PortfolioCrypto',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
                ('amount', models.FloatField(default=0)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.crypto')),
            ],
            options={
                'abstract': False,
            },
            bases=('portfolio.portfolio',),
        ),
    ]
