# Generated by Django 3.2 on 2021-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210727_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateportfolio',
            name='crypto_quantity',
            field=models.FloatField(default=0),
        ),
    ]
